# Site settings
title: BBI Family's Website
email: coming@soon.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://bbifam.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
